version: "3.8"
services:
  postgres:
    container_name: postgres
    image: 'postgres'
    ports:
      - '5400:5432'
    volumes:
      - budget:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: budget-management

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Welcome123
    depends_on:
      - postgres

  backend:
    build: ./expense-app-api
    ports:
      - '3100:3100'
    volumes:
      - ./expense-app-api:/app
      - /app/node_modules
    depends_on:
      - postgres

  frontend:
    build: ./expense-app-next-js
    ports:
      - '3000:3000'
    volumes:
      - ./expense-app-next-js/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  budget:
